package Craigbook::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Craigbook::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:ads.db',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

Craigbook::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Craigbook>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Craigbook::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

jack

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
